apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: naqdi-api-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: naqdi-api-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: naqdi-api-secret  # 👈 name of your AWS Secrets Manager entry

