daemonset:
  enabled: true

filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
    output.elasticsearch:
      hosts: ["http://elasticsearch-master:9200"]

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

